UPDATE stock_master SET stock_name_en = 'Korean Air' WHERE stock_code = '003490';
UPDATE stock_master SET stock_name_en = 'Korean Air Preferred' WHERE stock_code = '003495';
UPDATE stock_master SET stock_name_en = 'Asiana Airlines' WHERE stock_code = '020560';
UPDATE stock_master SET stock_name_en = 'EyesVision' WHERE stock_code = '031310';
UPDATE stock_master SET stock_name_en = 'LG Uplus' WHERE stock_code = '032640';
UPDATE stock_master SET stock_name_en = 'Digital Chosun' WHERE stock_code = '033130';
UPDATE stock_master SET stock_name_en = 'TBC' WHERE stock_code = '033830';
UPDATE stock_master SET stock_name_en = 'kt alpha' WHERE stock_code = '036030';
UPDATE stock_master SET stock_name_en = 'ContentreeJoongAng' WHERE stock_code = '036420';
UPDATE stock_master SET stock_name_en = 'Sejong Telecom' WHERE stock_code = '036630';
UPDATE stock_master SET stock_name_en = 'LG HelloVision' WHERE stock_code = '037560';
UPDATE stock_master SET stock_name_en = 'InfoBank' WHERE stock_code = '039290';
UPDATE stock_master SET stock_name_en = 'Korea Economic TV' WHERE stock_code = '039340';
UPDATE stock_master SET stock_name_en = 'KT Skylife' WHERE stock_code = '053210';
UPDATE stock_master SET stock_name_en = 'Hyundai Home Shopping' WHERE stock_code = '057050';
UPDATE stock_master SET stock_name_en = 'Wiable' WHERE stock_code = '065530';
UPDATE stock_master SET stock_name_en = 'CCS Chungbuk Broadcasting' WHERE stock_code = '066790';
UPDATE stock_master SET stock_name_en = 'Jeju Air' WHERE stock_code = '089590';
UPDATE stock_master SET stock_name_en = 'Trinity Airways' WHERE stock_code = '091810';
UPDATE stock_master SET stock_name_en = 'KX Innovation' WHERE stock_code = '122450';
UPDATE stock_master SET stock_name_en = 'Hyundai Futurenet' WHERE stock_code = '126560';
UPDATE stock_master SET stock_name_en = 'Asia Business Daily' WHERE stock_code = '127710';
UPDATE stock_master SET stock_name_en = 'Jin Air' WHERE stock_code = '272450';
UPDATE stock_master SET stock_name_en = 'Air Busan' WHERE stock_code = '298690';
